### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Raju** [ealush/wait#1]
@ealush when using
![image](https://user-images.githubusercontent.com/42042961/99907121-02324c00-2d01-11eb-9638-9ca79fd2daa9.png)
I get the below error in nodejs
![image](https://user-images.githubusercontent.com/42042961/99906885-8edc0a80-2cff-11eb-9eff-98188999099a.png)

When I add "type": "module" in package.json other things breaks
![image](https://user-images.githubusercontent.com/42042961/99906963-13c72400-2d00-11eb-8198-13ab8c7d9b19.png)

And when I use 
![image](https://user-images.githubusercontent.com/42042961/99907003-48d37680-2d00-11eb-85a6-0326dc384353.png)
everything works but as mentioned in readme - import wait from 'wait'; dosent work.

When I use it with live server on the browser side
![image](https://user-images.githubusercontent.com/42042961/99907139-1c6c2a00-2d01-11eb-8a28-6f53b1fe819e.png)
I get this error.
![image](https://user-images.githubusercontent.com/42042961/99907086-c6978200-2d00-11eb-97d7-23ee03ebacb1.png)

I'm confused atm, could someone explain. Can this run on both _nodejs_ and _browser if using live server_

What I'm doing wrong or right way to use it.

**Comment by ealush** [comment]
Hey @Raju, thanks for reaching out. I've replaced the build script from emitting a CJS only bundle to emitting multiple different bundles using [microbundle](https://github.com/developit/microbundle). I tested in different environments (not with live server, though). Can you confirm that it now works for you?

```npm i wait@0.4.2```

**Comment by Raju** [comment]
@ealush thanks for the update, once I get time ill check and update back.
